export {
  ANALYTICS_LABEL_MAX,
  ANALYTICS_LABEL_PATTERN,
  COORDINATE_BUCKETS,
  DEFAULT_SENSITIVE_ROUTE_PATTERNS,
  DEPLOYMENT_VERSION_MAX,
  ELEMENT_CATEGORIES,
  EVENT_ID_PATTERN,
  FORBIDDEN_EVENT_KEYS,
  MAX_BATCH_BYTES,
  MAX_EVENTS_PER_BATCH,
  ROUTE_MAX,
  SCROLL_MILESTONES,
  TAB_SESSION_PATTERN,
  TELEMETRY_EVENT_TYPES,
  TELEMETRY_SCHEMA_VERSION,
  VIEWPORT_GROUPS,
  bucketCoordinate,
  isAllowedAnalyticsLabel,
  viewportGroupFromWidth,
  type AnalyticsBootstrap,
  type ElementCategory,
  type TelemetryBatch,
  type TelemetryConsentState,
  type TelemetryEvent,
  type TelemetryEventType,
  type ViewportGroup,
} from "../../../packages/website-sdk/src/analytics/contract";
